[build]
  command = "npm run build"
  publish = "build"
  edge_functions = "functions"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version" 